// Generated by CoffeeScript 1.4.0
(function() {
  var buildSig, crypto, qs;

  crypto = require("crypto");

  qs = require("querystring");

  buildSig = function(params, secret) {
    var md5, name, reqString, sortedNames, sortedValues, _i, _len;
    sortedNames = Object.keys(params).sort(function(a, b) {
      return a.localeCompare(b);
    });
    sortedValues = [];
    for (_i = 0, _len = sortedNames.length; _i < _len; _i++) {
      name = sortedNames[_i];
      sortedValues.push("" + name + "=" + params[name]);
    }
    reqString = sortedValues.join("");
    reqString += secret;
    md5 = crypto.createHash("md5");
    md5.update(reqString);
    return md5.digest("hex");
  };

  module.exports = function(opts) {
    var key, secret;
    if (!opts || !opts.apiKey || !opts.apiSecret) {
      throw new Error("missing apiKey or apiSecret!");
    }
    key = opts.apiKey;
    secret = opts.apiSecret;
    opts.expires || (opts.expires = 1200);
    return function(mixUrl, params) {
      var pn, val;
      params.expire = Math.floor(Date.now() / 1000) + opts.expires;
      params.api_key = key;
      for (pn in params) {
        val = params[pn];
        if (Array.isArray(val)) {
          params[pn] = JSON.stringify(val);
        }
      }
      params["sig"] = buildSig(params, secret);
      return "" + mixUrl + "?" + (qs.stringify(params));
    };
  };

}).call(this);
